version: '3.7'

services:
  easy-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: easy-web:latest
    command: bash entrypoint.sh
    volumes:
      - .:/home/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      WAIT_HOSTS: easy-db
    depends_on:
      - db

  easy-db:
    image: postgres:12.0-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    env_file:
      - ./.env

  easy-nginx:
    build: ./docker_configs/nginx/

    ports:
      - "80"
      - "443"
    depends_on:
      - web

volumes:
  postgres_data:

networks:
  default:
    external: true
    name: easy-network


