# Generated by Django 3.1 on 2022-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_star',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Free'), (4, 'Four'), (5, 'Five')]),
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
