# Generated by Django 3.1 on 2022-01-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
