# Generated by Django 3.1 on 2022-01-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_avg_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='SignUpOrder',
        ),
    ]
