# Generated by Django 3.1 on 2022-01-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_auto_20211223_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
