# Generated by Django 3.1 on 2022-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_flat_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='arena_timeline',
            field=models.CharField(choices=[('OneDay', 'OneDay'), ('LongTime', 'LongTime')], max_length=200),
        ),
        migrations.AlterField(
            model_name='flat',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
